## 1 Import and Load Raw Data

In [1]:
import pandas as pd
import numpy as np
SOURCE_FILE = "Central_Superstore.xlsx"
SHEET_NAME = 'Central_Region'
df = pd.read_excel(SOURCE_FILE,sheet_name = SHEET_NAME)

df.dtypes
df.info()
df.shape
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2323 entries, 0 to 2322
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2323 non-null   int64
 1   Order ID       2323 non-null   object
 2   Order Date     2323 non-null   datetime64[ns]
 3   Ship Date      2323 non-null   datetime64[ns]
 4   Ship Mode      2323 non-null   object
 5   Customer ID    2323 non-null   object
 6   Customer Name  2323 non-null   object
 7   Segment        2323 non-null   object
 8   Country        2323 non-null   object
 9   City           2323 non-null   object
 10  State          2323 non-null   object
 11  Postal Code    2323 non-null   int64
 12  Region         2323 non-null   object
 13  Product ID     2323 non-null   object
 14  Category       2323 non-null   object
 15  Sub-Category   2323 non-null   object
 16  Product Name   2323 non-null   object
 17  Sales          2323 non-null   float64
 18  Quantity       2323 non-null   int64
 19  Discount       2323 non-null   float64
 20  Profit         2323 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 381.2+ KB

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,15,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580
1,16,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.8160
2,17,CA-2011-105893,2013-11-11,2013-11-18,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,53711,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.880,6,0.0,13.3176
3,22,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025,Central,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.460,7,0.0,5.0596
4,23,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340,7,0.0,15.6884

In [2]:
df2=pd.ExcelFile("Central_Superstore.xlsx")
print(df2.sheet_names)

['Central_Region']

## 2 Profile data before cleaning

In [ ]:
# Profile Product
product_profile = df.groupby("Product ID")[["Product Name", "Category", "Sub-Category"]].nunique() 
print("Product IDs with > 1 name:", (product_profile["Product Name"] > 1).sum())
print("Product IDs with > 1 category:", (product_profile["Category"] > 1).sum())
print("Product IDs with > 1 sub-category:", (product_profile["Sub-Category"] > 1).sum())

In [ ]:
# Profile Customers
cust_profile = df.groupby("Customer ID")[["Customer Name", "Segment"]].nunique()    
print("Customer IDs with > 1 name:", (cust_profile["Customer Name"] > 1).sum())
print("Customer IDs with > 1 segment:", (cust_profile["Segment"] > 1).sum())

## 3 Cleaning Data

In [3]:
# check nulls
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [4]:
# check duplicate
df.duplicated().sum()

np.int64(0)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [6]:
df[df['Order Date']>df['Ship Date']]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [7]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [8]:
df["Postal Code"] = df["Postal Code"].astype(str).str.zfill(5)

In [9]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code              object
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [10]:
df[df["Postal Code"].str.startswith("0")]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [11]:
df.columns = (df.columns
.str.replace(" ","_" ,regex = False)
.str.strip()
.str.replace("-","_" ,regex = False)
.str.lower()
            )
print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [12]:
text_cols = ['order_id',  'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name']
for c in text_cols:
    df[c] = df[c].astype(str).str.strip()

In [13]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
0,15,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580
1,16,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.8160
2,17,CA-2011-105893,2013-11-11,2013-11-18,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,53711,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.880,6,0.0,13.3176
3,22,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025,Central,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.460,7,0.0,5.0596
4,23,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,68025,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340,7,0.0,15.6884

In [14]:
df["discount"].unique()

array([0.8 , 0.  , 0.2 , 0.6 , 0.32, 0.3 , 0.5 , 0.4 , 0.1 ])

In [15]:
df[df["sales"]<=0]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [16]:
df[df["quantity"] <= 0]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [17]:
df["profit"].max()

8399.975999999999

In [18]:
df["profit"].min()

-3701.8928000000014

## 4. Building Dimension Tables

In [19]:
all_dates = pd.concat([df["order_date"],df["ship_date"]]).drop_duplicates().sort_values()
print(all_dates)
print(type(all_dates))

1809   2013-01-03
188    2013-01-04
1752   2013-01-07
188    2013-01-08
152    2013-01-09
          ...
163    2016-12-30
237    2017-01-01
1716   2017-01-02
991    2017-01-04
163    2017-01-05
Length: 1058, dtype: datetime64[ns]
<class 'pandas.core.series.Series'>

### 4.1 Dim Date

In [20]:
dim_date = pd.DataFrame({'full_date':all_dates})

dim_date["date_key"] = dim_date["full_date"].dt.strftime("%y%m%d").astype(int)
dim_date["year"] = dim_date["full_date"].dt.year
dim_date["quarter"] = dim_date["full_date"].dt.quarter
dim_date["month"] = dim_date["full_date"].dt.month
dim_date["month_name"] = dim_date["full_date"].dt.month_name()
dim_date["day"] = dim_date["full_date"].dt.day
dim_date["day_name"] = dim_date["full_date"].dt.day_name()
dim_date["week_of_year"] = dim_date["full_date"].dt.isocalendar().week.astype(int)
dim_date["is_weekend"] = dim_date["full_date"].dt.dayofweek >= 5

dim_date = dim_date[["date_key","full_date","year", "quarter", "month", "month_name",
                     "day", "day_name","week_of_year", "is_weekend"]].reset_index(drop=True)

### 4.2 dim_product

In [21]:
dim_product =( df[["product_id","category","sub_category","product_name"]]
.drop_duplicates().sort_values(["product_id", "product_name"]).reset_index(drop = True)
    )
dim_product.insert(0, "product_key", dim_product.index + 1)

### 4.3 dim_customer

In [22]:
dim_customer = ( df[["customer_id","customer_name","segment"]].drop_duplicates()
.sort_values(["customer_id"])
.reset_index(drop = True))
dim_customer.insert(0,"customer_key", dim_customer.index +1)

### 4.4 dim_location

In [23]:
dim_location = (df[["country","city","state","postal_code","region"]].drop_duplicates()
.sort_values(["country","city","state","postal_code","region"]).reset_index(drop = True)
               )
dim_location.insert(0,"location_key",dim_location.index +1)

### 4.5 dim_ship_mode

In [24]:
dim_ship_mode = df[["ship_mode"]].drop_duplicates().sort_values("ship_mode").reset_index(drop=True)
dim_ship_mode.insert(0, "ship_mode_key", dim_ship_mode.index + 1)

## 5 Building Fact Table

In [25]:
fact_table = df.merge(dim_customer, on=["customer_id","customer_name","segment"], how="left") \
                .merge(dim_product, on=["product_id","product_name","category","sub_category"], how="left") \
                .merge(dim_location,
                       on=["country","region","state","city","postal_code"], how="left") \
                .merge(dim_ship_mode, on="ship_mode", how="left") \
                .merge(dim_date[["date_key","full_date"]].rename(columns={"date_key":"order_date_key","full_date":"order_date"}), 
                       on = "order_date", how="left") \
                .merge(dim_date[["date_key","full_date"]].rename(columns={"date_key":"ship_date_key","full_date":"ship_date"}), 
                       on = "ship_date", how="left")

In [26]:
fact_table.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,customer_key,product_key,location_key,ship_mode_key,order_date_key,ship_date_key
0,15,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,68.810,5,0.8,-123.8580,263,310,63,4,141122,141126
1,16,US-2012-118983,2014-11-22,2014-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,2.544,3,0.8,-3.8160,263,479,63,4,141122,141126
2,17,CA-2011-105893,2013-11-11,2013-11-18,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,...,665.880,6,0.0,13.3176,463,1032,109,4,131111,131118
3,22,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,19.460,7,0.0,5.0596,323,354,67,4,151210,151214
4,23,CA-2013-137330,2015-12-10,2015-12-14,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,...,60.340,7,0.0,15.6884,323,298,67,4,151210,151214

In [27]:
fact_table = fact_table[["row_id","order_id","order_date_key","ship_date_key",
                        "ship_mode_key", "customer_key","location_key","product_key",
                        "sales","quantity","discount","profit"]].rename(columns={"row_id":"sales_key"}).sort_values("sales_key").reset_index(drop=True)

In [28]:
fact_table.head()

,sales_key,order_id,order_date_key,ship_date_key,ship_mode_key,customer_key,location_key,product_key,sales,quantity,discount,profit
0,15,US-2012-118983,141122,141126,4,263,63,310,68.810,5,0.8,-123.8580
1,16,US-2012-118983,141122,141126,4,263,63,479,2.544,3,0.8,-3.8160
2,17,CA-2011-105893,131111,131118,4,463,109,1032,665.880,6,0.0,13.3176
3,22,CA-2013-137330,151210,151214,4,323,67,354,19.460,7,0.0,5.0596
4,23,CA-2013-137330,151210,151214,4,323,67,298,60.340,7,0.0,15.6884

## 6 Connecting to SQL Server

In [29]:
from sqlalchemy import create_engine, text
import warnings
warnings.filterwarnings("ignore", category=Warning)

SQL_SERVER = "localhost"
SQL_DATABASE = "SuperstoreCR"
SQL_DRIVER = "ODBC Driver 17 for SQL Server"

conn_str = (
    f"mssql+pyodbc://@{SQL_SERVER}/{SQL_DATABASE}"
    f"?driver={SQL_DRIVER.replace(' ', '+')}&trusted_connection=yes"
)

engine = create_engine(conn_str, fast_executemany=True)
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT @@VERSION"))
        print(result.fetchone()[0])
except Exception as e:
    print("Connection Failed", e)

Microsoft SQL Server 2025 (RTM-GDR) (KB5122770) - 17.0.1135.8 (X64)
	Aug 20 2026 00:56:11
	Copyright (C) 2025 Microsoft Corporation
	Standard Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: )

## 7 Create the schema and tables

In [30]:
ddl_statements =["""
create table dbo.dim_product(product_key INT PRIMARY KEY,
    
product_id VARCHAR(25) NOT NULL,
category VARCHAR(20) NOT NULL,
sub_category VARCHAR(20) NOT NULL,
product_name VARCHAR(500) NOT NULL);
    """,
    """
create table dbo.dim_customer(customer_key INT PRIMARY KEY,
customer_id VARCHAR(20) NOT NULL,
customer_name VARCHAR(25) NOT NULL,
segment VARCHAR(20) NOT NULL);
    """,
    """
create table dbo.dim_location(location_key INT PRIMARY KEY,
country VARCHAR(50) NOT NULL,
state VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL,
postal_code INT NOT NULL,
region VARCHAR(50) NOT NULL);
    """,
    """
create table dbo.dim_ship_mode(ship_mode_key INT PRIMARY KEY,
ship_mode VARCHAR(20) NOT NULL);
    """,
    """
 CREATE TABLE dbo.dim_date (
        date_key INT PRIMARY KEY,
        full_date DATE NOT NULL,
        year SMALLINT NOT NULL,
        quarter TINYINT NOT NULL,
        month SMALLINT NOT NULL,
        month_name VARCHAR(15) NOT NULL,
        day TINYINT NOT NULL,
        day_name VARCHAR(15) NOT NULL,
        week_of_year TINYINT NOT NULL,
        is_weekend BIT NOT NULL);
    """,
    """
 CREATE TABLE dbo.fact_table (
        sales_key INT PRIMARY KEY,
        order_id VARCHAR(20) NOT NULL,
        order_date_key INT NOT NULL,
        ship_date_key INT NOT NULL,
        ship_mode_key INT NOT NULL,
        customer_key INT NOT NULL,
        location_key INT NOT NULL,
        product_key INT NOT NULL,
        sales DECIMAL(12,4) NOT NULL,
        quantity INT NOT NULL,
        discount DECIMAL(5,4) NOT NULL,
        profit DECIMAL(12,4) NOT NULL,

        CONSTRAINT fk_fact_order_date FOREIGN KEY (order_date_key) REFERENCES dbo.dim_date(date_key),
        CONSTRAINT fk_fact_ship_date FOREIGN KEY (ship_date_key) REFERENCES dbo.dim_date(date_key),
        CONSTRAINT fk_fact_ship_mode FOREIGN KEY (ship_mode_key) REFERENCES dbo.dim_ship_mode(ship_mode_key),
        CONSTRAINT fk_fact_customer FOREIGN KEY (customer_key) REFERENCES dbo.dim_customer(customer_key),
        CONSTRAINT fk_fact_product FOREIGN KEY (product_key) REFERENCES dbo.dim_product(product_key),
        CONSTRAINT fk_fact_location FOREIGN KEY (location_key) REFERENCES dbo.dim_location(location_key)
    );
    """
]







with engine.begin() as conn:
    for stmt in ddl_statements:
        conn.execute(text(stmt))

print("ALL TABLES CREATED")

ALL TABLES CREATED

## 8 Load Data into SQL Server Tables

In [31]:
load_order = [
    ("dim_date", dim_date),
    ("dim_product",dim_product),
 ("dim_ship_mode", dim_ship_mode),
    ("dim_customer", dim_customer),
    ("dim_location", dim_location),
    ("fact_table", fact_table)
]

for table_name, df in load_order:
    df.to_sql(table_name, con=engine, schema="dbo", if_exists="append",
             index=False, chunksize=1000)
    print(f"Loaded {len(df)} rows --into--> dbo.{table_name}")

Loaded 1058 rows --into--> dbo.dim_date
Loaded 1326 rows --into--> dbo.dim_product
Loaded 4 rows --into--> dbo.dim_ship_mode
Loaded 629 rows --into--> dbo.dim_customer
Loaded 195 rows --into--> dbo.dim_location
Loaded 2323 rows --into--> dbo.fact_table